export const IPC_CHANNELS = {
  appWarmUp: 'app:warmUp',
  downloadsStart: 'downloads:start',
  downloadsCancel: 'downloads:cancel',
  downloadsPause: 'downloads:pause',
  downloadsGetFormats: 'downloads:getFormats',
  chooseFolder: 'dialog:chooseFolder',
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  shellOpenFolder: 'shell:openFolder',
  shellOpenExternal: 'shell:openExternal',
  logsOpenDir: 'logs:openDir',
  eventsStatus: 'events:status',
  eventsProgress: 'events:progress',
  windowMinimize: 'window:minimize',
  windowMaximize: 'window:maximize',
  windowClose: 'window:close',
  windowIsMaximized: 'window:isMaximized',
  windowMaximizedChange: 'window:maximizedChange',
} as const;
