// Regenerates per-tool agent adapters from the shared `.agents/` sources.
// `.agents/skills/` and `.agents/mcp.json` are the only tracked inputs; every
// output here is gitignored local state, safe to delete and rebuild.
import {lstat, mkdir, readdir, readFile, rm, stat, symlink, writeFile} from 'node:fs/promises'
import path from 'node:path'
import {fileURLToPath} from 'node:url'
import {z} from 'zod'

const mcpServerSchema = z.strictObject({command: z.string().min(1), args: z.array(z.string()).default([])})
const agentsMcpConfigSchema = z.strictObject({servers: z.record(z.string().min(1), mcpServerSchema)})

export type AgentsMcpConfig = z.infer<typeof agentsMcpConfigSchema>

// Claude Code is the only supported tool that does not read `.agents/skills` natively
// (Codex and OpenCode both do), so it is the only skill adapter.
const CLAUDE_SKILLS_DIR = '.claude/skills'

export function parseAgentsMcpConfig(value: unknown): AgentsMcpConfig {
	return agentsMcpConfigSchema.parse(value)
}

// JSON string literals are valid TOML basic strings: every JSON escape is also a TOML escape.
const tomlString = (value: string): string => JSON.stringify(value)

function renderCodexToml(config: AgentsMcpConfig): string {
	return Object.entries(config.servers)
		.map(([name, server]) => `[mcp_servers.${tomlString(name)}]\ncommand = ${tomlString(server.command)}\nargs = [${server.args.map(tomlString).join(', ')}]\n`)
		.join('\n')
}

const json = (value: unknown): string => `${JSON.stringify(value, null, '\t')}\n`

export function renderMcpTargets(config: AgentsMcpConfig): Record<'.mcp.json' | '.codex/config.toml' | 'opencode.jsonc', string> {
	const servers = Object.entries(config.servers)
	return {
		'.mcp.json': json({mcpServers: Object.fromEntries(servers.map(([name, s]) => [name, {type: 'stdio', command: s.command, args: s.args}]))}),
		'.codex/config.toml': `# Generated by \`bun run agents:sync\` from .agents/mcp.json — do not edit.\n${renderCodexToml(config)}`,
		'opencode.jsonc': json({$schema: 'https://opencode.ai/config.json', mcp: Object.fromEntries(servers.map(([name, s]) => [name, {type: 'local', command: [s.command, ...s.args], enabled: true}]))})
	}
}

async function exists(target: string): Promise<boolean> {
	return stat(target).then(
		() => true,
		() => false
	)
}

async function listSharedSkills(repoRoot: string): Promise<string[]> {
	const dir = path.join(repoRoot, '.agents/skills')
	if (!(await exists(dir))) return []
	const entries = await readdir(dir, {withFileTypes: true})
	const names = await Promise.all(entries.map(async entry => ((entry.isDirectory() || entry.isSymbolicLink()) && (await exists(path.join(dir, entry.name, 'SKILL.md'))) ? entry.name : null)))
	return names.filter((name): name is string => name !== null).sort()
}

async function syncClaudeSkillLinks(repoRoot: string): Promise<void> {
	const linkDir = path.join(repoRoot, CLAUDE_SKILLS_DIR)
	await mkdir(linkDir, {recursive: true})

	for (const entry of await readdir(linkDir, {withFileTypes: true})) {
		const link = path.join(linkDir, entry.name)
		if (entry.isSymbolicLink() && !(await exists(link))) await rm(link)
	}

	for (const name of await listSharedSkills(repoRoot)) {
		const link = path.join(linkDir, name)
		const current = await lstat(link).catch(() => null)
		if (current && !current.isSymbolicLink()) {
			console.warn(`agents:sync: leaving ${CLAUDE_SKILLS_DIR}/${name} alone — it is not a link`)
			continue
		}
		if (current) await rm(link)
		// Junctions need no Windows symlink privilege but require an absolute target.
		if (process.platform === 'win32') await symlink(path.join(repoRoot, '.agents/skills', name), link, 'junction')
		else await symlink(path.join('../../.agents/skills', name), link)
	}
}

async function writeMcpTargets(repoRoot: string): Promise<void> {
	const source = path.join(repoRoot, '.agents/mcp.json')
	if (!(await exists(source))) return
	const config = parseAgentsMcpConfig(JSON.parse(await readFile(source, 'utf8')))
	for (const [target, content] of Object.entries(renderMcpTargets(config))) {
		await mkdir(path.dirname(path.join(repoRoot, target)), {recursive: true})
		await writeFile(path.join(repoRoot, target), content)
	}
}

export async function syncAgents(repoRoot: string): Promise<void> {
	await syncClaudeSkillLinks(repoRoot)
	await writeMcpTargets(repoRoot)
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
	await syncAgents(process.cwd())
	console.log('agents:sync complete')
}
