// Landing-page translations. One object per locale; every locale must
// define every key (build.mjs validates parity at build time).
//
// Keys ending in `_html` are injected as raw HTML so translations can
// keep inline tags like <em>. Everything else is HTML-escaped.

export const en = {
  title: "Arroxy — Free Open-Source YouTube Downloader",
  description:
    "Download YouTube videos in 4K, 1080p60 and HDR. Free, ad-free, no login, no cookies, 100% private. Windows, macOS, Linux.",
  og_title: "Arroxy — Free Open-Source YouTube Downloader",
  og_description:
    "4K · 1080p60 · HDR · Shorts. No ads. No tracking. No cookies. No login.",

  nav_features: "Features",
  nav_screenshots: "Screenshots",
  nav_install: "Install",
  nav_download: "Download",

  hero_eyebrow: "Modern · Free · Open Source",
  hero_h1_a: "Download YouTube videos",
  hero_h1_b: "in full quality.",
  hero_tagline:
    "Anything YouTube serves — 4K, 1080p60, HDR, Shorts — straight to your disk.",
  pill_no_ads: "No ads",
  pill_no_tracking: "No tracking",
  pill_no_login: "No login",
  pill_no_cookies: "No cookies",
  pill_mit: "MIT licensed",
  cta_download_os: "Download for your OS",
  cta_view_github: "View on GitHub",
  release_label: "Latest release:",
  release_loading: "loading…",

  features_eyebrow: "What it does",
  features_h2: "Everything you'd expect, none of the friction.",
  features_sub: "Paste a URL, pick a quality, click download. That's it.",
  f1_h: "Up to 4K UHD",
  f1_p: "2160p, 1440p, 1080p, 720p — every resolution YouTube offers, plus audio-only MP3, AAC, and Opus.",
  f2_h: "60 fps & HDR preserved",
  f2_p: "High frame-rate and HDR streams come through exactly as YouTube encodes them — no quality loss.",
  f3_h: "Multiple at once",
  f3_p: "Queue as many videos as you want. The download panel tracks progress for each in parallel.",
  f4_h: "Auto-updates",
  f4_p: "Arroxy keeps yt-dlp and ffmpeg fresh under the hood — works through every YouTube change.",
  f5_h: "9 languages",
  f5_p: "English, Español, Deutsch, Français, 日本語, 中文, Русский, Українська, हिन्दी — auto-detects yours.",
  f6_h: "Cross-platform",
  f6_p: "Native builds for Windows, macOS, and Linux — installer, portable, DMG, or AppImage.",
  f7_h: "Subtitles, your way",
  f7_p: "Manual or auto-generated captions in SRT, VTT, or ASS — saved beside the video, embedded into a portable .mkv, or tucked into a Subtitles/ folder.",
  f8_h: "SponsorBlock built in",
  f8_p: "Skip or mark sponsor segments, intros, outros, self-promos, and more — cut them with FFmpeg or just add chapters. Your call, per category.",

  shots_eyebrow: "See it in action",
  shots_h2: "Built for clarity, not clutter.",
  shot1_alt: "Paste a URL",
  shot2_alt: "Pick your quality",
  shot3_alt: "Choose where to save",
  shot4_alt: "Parallel downloads",
  shot5_alt: "Subtitles step — pick languages, format, and save mode",
  og_image_alt: "Arroxy app icon — desktop app for downloading YouTube videos in 4K.",

  privacy_eyebrow: "Privacy",
  privacy_h2_html: "What Arroxy <em>doesn't</em> do.",
  privacy_sub:
    "Most YouTube downloaders eventually ask for your cookies. Arroxy never will.",
  p1_h: "No login",
  p1_p: "No Google account. No sessions to expire. Zero risk of your account getting flagged.",
  p2_h: "No cookies",
  p2_p: "Arroxy requests the same tokens any browser does. Nothing exported, nothing stored.",
  p3_h: "No telemetry",
  p3_p: "Zero analytics. Your downloads, history, and files stay on your device — full stop.",
  p4_h: "No third-party servers",
  p4_p: "The whole pipeline runs locally via yt-dlp + ffmpeg. Files never touch a remote server.",

  install_eyebrow: "Install",
  install_h2: "Pick your channel.",
  install_sub:
    "Direct download or any major package manager — all auto-updated each release.",
  badge_windows: "Windows",
  badge_macos: "macOS",
  badge_all: "All",
  winget_desc: "Recommended for Windows 10/11. Auto-updates with the system.",
  scoop_desc: "Portable install via Scoop bucket. No admin rights needed.",
  brew_desc: "Tap the cask, install with one command. Universal binary (Intel + Apple Silicon).",
  direct_h: "Direct download",
  direct_desc: "NSIS installer, portable .exe, .dmg, or .AppImage — straight from GitHub Releases.",
  direct_btn: "Open Releases →",
  copy_label: "Copy",
  copied_label: "Copied!",

  footer_made_by: "MIT Licensed · Made with care by",
  footer_github: "GitHub",
  footer_issues: "Issues",
  footer_releases: "Releases",
  footer_languages_label: "Language:",
};

export const es = {
  title: "Arroxy — Descargador de YouTube gratuito y de código abierto",
  description:
    "Descarga videos de YouTube en 4K, 1080p60 y HDR. Gratis, sin anuncios, sin inicio de sesión, sin cookies, 100% privado. Windows, macOS, Linux.",
  og_title: "Arroxy — Descargador de YouTube gratuito y de código abierto",
  og_description:
    "4K · 1080p60 · HDR · Shorts. Sin anuncios. Sin rastreo. Sin cookies. Sin inicio de sesión.",

  nav_features: "Funciones",
  nav_screenshots: "Capturas",
  nav_install: "Instalar",
  nav_download: "Descargar",

  hero_eyebrow: "Moderno · Gratis · Código abierto",
  hero_h1_a: "Descarga videos de YouTube",
  hero_h1_b: "en calidad completa.",
  hero_tagline:
    "Todo lo que YouTube ofrece — 4K, 1080p60, HDR, Shorts — directo a tu disco.",
  pill_no_ads: "Sin anuncios",
  pill_no_tracking: "Sin rastreo",
  pill_no_login: "Sin inicio de sesión",
  pill_no_cookies: "Sin cookies",
  pill_mit: "Licencia MIT",
  cta_download_os: "Descargar para tu SO",
  cta_view_github: "Ver en GitHub",
  release_label: "Última versión:",
  release_loading: "cargando…",

  features_eyebrow: "Qué hace",
  features_h2: "Todo lo que esperas, sin fricción.",
  features_sub: "Pega una URL, elige la calidad, haz clic en descargar. Así de simple.",
  f1_h: "Hasta 4K UHD",
  f1_p: "2160p, 1440p, 1080p, 720p — todas las resoluciones que ofrece YouTube, además de audio MP3, AAC y Opus.",
  f2_h: "60 fps y HDR preservados",
  f2_p: "Las transmisiones de alta tasa de fotogramas y HDR llegan tal como las codifica YouTube — sin pérdida de calidad.",
  f3_h: "Varios a la vez",
  f3_p: "Pon en cola tantos videos como quieras. El panel de descargas muestra el progreso de cada uno en paralelo.",
  f4_h: "Actualizaciones automáticas",
  f4_p: "Arroxy mantiene yt-dlp y ffmpeg al día — funciona con cada cambio de YouTube.",
  f5_h: "9 idiomas",
  f5_p: "English, Español, Deutsch, Français, 日本語, 中文, Русский, Українська, हिन्दी — detecta el tuyo automáticamente.",
  f6_h: "Multiplataforma",
  f6_p: "Compilaciones nativas para Windows, macOS y Linux — instalador, portátil, DMG o AppImage.",
  f7_h: "Subtítulos a tu manera",
  f7_p: "Subtítulos manuales o automáticos en SRT, VTT o ASS — junto al video, integrados en un .mkv portátil, o en una subcarpeta Subtitles/.",
  f8_h: "SponsorBlock integrado",
  f8_p: "Omite o marca segmentos de patrocinadores, intros, outros, autopromociones y más — recórtalos con FFmpeg o simplemente añade capítulos. Tú decides, por categoría.",

  shots_eyebrow: "Velo en acción",
  shots_h2: "Diseñado para la claridad, no para el desorden.",
  shot1_alt: "Pega una URL",
  shot2_alt: "Elige tu calidad",
  shot3_alt: "Elige dónde guardar",
  shot4_alt: "Descargas en paralelo",
  shot5_alt: "Paso de subtítulos — elige idiomas, formato y modo de guardado",
  og_image_alt: "Icono de la app Arroxy — app de escritorio para descargar videos de YouTube en 4K.",

  privacy_eyebrow: "Privacidad",
  privacy_h2_html: "Lo que Arroxy <em>no</em> hace.",
  privacy_sub:
    "La mayoría de descargadores de YouTube acaban pidiendo tus cookies. Arroxy nunca lo hará.",
  p1_h: "Sin inicio de sesión",
  p1_p: "Sin cuenta de Google. Sin sesiones que caducan. Cero riesgo de que marquen tu cuenta.",
  p2_h: "Sin cookies",
  p2_p: "Arroxy solicita los mismos tokens que cualquier navegador. Nada se exporta, nada se almacena.",
  p3_h: "Sin telemetría",
  p3_p: "Cero analítica. Tus descargas, historial y archivos se quedan en tu dispositivo — punto final.",
  p4_h: "Sin servidores de terceros",
  p4_p: "Todo el proceso se ejecuta localmente con yt-dlp + ffmpeg. Los archivos nunca tocan un servidor remoto.",

  install_eyebrow: "Instalar",
  install_h2: "Elige tu canal.",
  install_sub:
    "Descarga directa o cualquier gestor de paquetes — todos se actualizan automáticamente con cada versión.",
  badge_windows: "Windows",
  badge_macos: "macOS",
  badge_all: "Todo",
  winget_desc: "Recomendado para Windows 10/11. Se actualiza con el sistema.",
  scoop_desc: "Instalación portátil vía Scoop bucket. No requiere permisos de administrador.",
  brew_desc: "Añade el tap, instala con un comando. Binario universal (Intel + Apple Silicon).",
  direct_h: "Descarga directa",
  direct_desc: "Instalador NSIS, .exe portátil, .dmg o .AppImage — directo desde GitHub Releases.",
  direct_btn: "Abrir Releases →",
  copy_label: "Copiar",
  copied_label: "¡Copiado!",

  footer_made_by: "Licencia MIT · Hecho con cariño por",
  footer_github: "GitHub",
  footer_issues: "Issues",
  footer_releases: "Releases",
  footer_languages_label: "Idioma:",
};

export const de = {
  title: "Arroxy — Kostenloser Open-Source YouTube-Downloader",
  description:
    "Lade YouTube-Videos in 4K, 1080p60 und HDR herunter. Kostenlos, werbefrei, kein Login, keine Cookies, 100% privat. Windows, macOS, Linux.",
  og_title: "Arroxy — Kostenloser Open-Source YouTube-Downloader",
  og_description:
    "4K · 1080p60 · HDR · Shorts. Keine Werbung. Kein Tracking. Keine Cookies. Kein Login.",

  nav_features: "Funktionen",
  nav_screenshots: "Screenshots",
  nav_install: "Installation",
  nav_download: "Download",

  hero_eyebrow: "Modern · Kostenlos · Open Source",
  hero_h1_a: "Lade YouTube-Videos",
  hero_h1_b: "in voller Qualität.",
  hero_tagline:
    "Alles, was YouTube anbietet — 4K, 1080p60, HDR, Shorts — direkt auf deine Festplatte.",
  pill_no_ads: "Keine Werbung",
  pill_no_tracking: "Kein Tracking",
  pill_no_login: "Kein Login",
  pill_no_cookies: "Keine Cookies",
  pill_mit: "MIT-Lizenz",
  cta_download_os: "Für dein Betriebssystem herunterladen",
  cta_view_github: "Auf GitHub ansehen",
  release_label: "Neueste Version:",
  release_loading: "wird geladen…",

  features_eyebrow: "Was es kann",
  features_h2: "Alles, was du erwartest — ganz ohne Reibung.",
  features_sub: "URL einfügen, Qualität wählen, Download klicken. Mehr nicht.",
  f1_h: "Bis zu 4K UHD",
  f1_p: "2160p, 1440p, 1080p, 720p — jede Auflösung, die YouTube bietet, plus Audio-only MP3, AAC und Opus.",
  f2_h: "60 fps & HDR erhalten",
  f2_p: "High-Framerate- und HDR-Streams kommen genau so durch, wie YouTube sie kodiert — ohne Qualitätsverlust.",
  f3_h: "Mehrere gleichzeitig",
  f3_p: "Reihe so viele Videos in die Warteschlange ein, wie du willst. Das Download-Panel verfolgt jeden Fortschritt parallel.",
  f4_h: "Auto-Updates",
  f4_p: "Arroxy hält yt-dlp und ffmpeg im Hintergrund aktuell — funktioniert nach jeder YouTube-Änderung.",
  f5_h: "9 Sprachen",
  f5_p: "English, Español, Deutsch, Français, 日本語, 中文, Русский, Українська, हिन्दी — erkennt deine automatisch.",
  f6_h: "Plattformübergreifend",
  f6_p: "Native Builds für Windows, macOS und Linux — Installer, Portable, DMG oder AppImage.",
  f7_h: "Untertitel, wie du willst",
  f7_p: "Manuelle oder automatisch generierte Untertitel in SRT, VTT oder ASS — neben dem Video gespeichert, in eine portable .mkv eingebettet oder in einen Subtitles/-Ordner sortiert.",
  f8_h: "SponsorBlock integriert",
  f8_p: "Überspringe oder markiere Sponsor-Segmente, Intros, Outros, Eigenwerbung und mehr — schneide sie mit FFmpeg heraus oder füge einfach Kapitel hinzu. Deine Wahl, pro Kategorie.",

  shots_eyebrow: "In Aktion sehen",
  shots_h2: "Gebaut für Klarheit, nicht für Chaos.",
  shot1_alt: "URL einfügen",
  shot2_alt: "Qualität wählen",
  shot3_alt: "Speicherort wählen",
  shot4_alt: "Parallele Downloads",
  shot5_alt: "Untertitel-Schritt — Sprachen, Format und Speichermodus wählen",
  og_image_alt: "Arroxy App-Icon — Desktop-App zum Herunterladen von YouTube-Videos in 4K.",

  privacy_eyebrow: "Privatsphäre",
  privacy_h2_html: "Was Arroxy <em>nicht</em> tut.",
  privacy_sub:
    "Die meisten YouTube-Downloader fragen irgendwann nach deinen Cookies. Arroxy niemals.",
  p1_h: "Kein Login",
  p1_p: "Kein Google-Konto. Keine ablaufenden Sitzungen. Null Risiko, dass dein Konto markiert wird.",
  p2_h: "Keine Cookies",
  p2_p: "Arroxy fordert dieselben Tokens an wie jeder Browser. Nichts exportiert, nichts gespeichert.",
  p3_h: "Keine Telemetrie",
  p3_p: "Null Analytics. Deine Downloads, Verlauf und Dateien bleiben auf deinem Gerät — Punkt.",
  p4_h: "Keine Drittanbieter-Server",
  p4_p: "Die ganze Pipeline läuft lokal über yt-dlp + ffmpeg. Dateien berühren nie einen Remote-Server.",

  install_eyebrow: "Installation",
  install_h2: "Wähle deinen Kanal.",
  install_sub:
    "Direkter Download oder ein gängiger Paketmanager — alle aktualisieren sich automatisch mit jedem Release.",
  badge_windows: "Windows",
  badge_macos: "macOS",
  badge_all: "Alle",
  winget_desc: "Empfohlen für Windows 10/11. Aktualisiert sich mit dem System.",
  scoop_desc: "Portable Installation via Scoop-Bucket. Keine Admin-Rechte nötig.",
  brew_desc: "Cask hinzufügen, mit einem Befehl installieren. Universal Binary (Intel + Apple Silicon).",
  direct_h: "Direkter Download",
  direct_desc: "NSIS-Installer, portable .exe, .dmg oder .AppImage — direkt von GitHub Releases.",
  direct_btn: "Releases öffnen →",
  copy_label: "Kopieren",
  copied_label: "Kopiert!",

  footer_made_by: "MIT-Lizenz · Mit Sorgfalt gemacht von",
  footer_github: "GitHub",
  footer_issues: "Issues",
  footer_releases: "Releases",
  footer_languages_label: "Sprache:",
};

export const fr = {
  title: "Arroxy — Téléchargeur YouTube gratuit et open source",
  description:
    "Téléchargez des vidéos YouTube en 4K, 1080p60 et HDR. Gratuit, sans pub, sans connexion, sans cookies, 100% privé. Windows, macOS, Linux.",
  og_title: "Arroxy — Téléchargeur YouTube gratuit et open source",
  og_description:
    "4K · 1080p60 · HDR · Shorts. Sans pub. Sans pistage. Sans cookies. Sans connexion.",

  nav_features: "Fonctionnalités",
  nav_screenshots: "Captures",
  nav_install: "Installer",
  nav_download: "Télécharger",

  hero_eyebrow: "Moderne · Gratuit · Open Source",
  hero_h1_a: "Téléchargez les vidéos YouTube",
  hero_h1_b: "en pleine qualité.",
  hero_tagline:
    "Tout ce que YouTube propose — 4K, 1080p60, HDR, Shorts — directement sur votre disque.",
  pill_no_ads: "Sans pub",
  pill_no_tracking: "Sans pistage",
  pill_no_login: "Sans connexion",
  pill_no_cookies: "Sans cookies",
  pill_mit: "Licence MIT",
  cta_download_os: "Télécharger pour votre OS",
  cta_view_github: "Voir sur GitHub",
  release_label: "Dernière version :",
  release_loading: "chargement…",

  features_eyebrow: "Ce qu'il fait",
  features_h2: "Tout ce que vous attendez, sans la moindre friction.",
  features_sub: "Collez une URL, choisissez une qualité, cliquez sur télécharger. C'est tout.",
  f1_h: "Jusqu'à 4K UHD",
  f1_p: "2160p, 1440p, 1080p, 720p — toutes les résolutions proposées par YouTube, plus l'audio seul en MP3, AAC et Opus.",
  f2_h: "60 fps et HDR préservés",
  f2_p: "Les flux haute fréquence d'images et HDR passent exactement comme YouTube les encode — sans perte de qualité.",
  f3_h: "Plusieurs à la fois",
  f3_p: "Mettez autant de vidéos que vous voulez en file d'attente. Le panneau suit la progression de chacune en parallèle.",
  f4_h: "Mises à jour automatiques",
  f4_p: "Arroxy garde yt-dlp et ffmpeg à jour en coulisse — résiste à chaque changement de YouTube.",
  f5_h: "9 langues",
  f5_p: "English, Español, Deutsch, Français, 日本語, 中文, Русский, Українська, हिन्दी — détecte la vôtre automatiquement.",
  f6_h: "Multiplateforme",
  f6_p: "Builds natifs pour Windows, macOS et Linux — installeur, portable, DMG ou AppImage.",
  f7_h: "Sous-titres comme tu veux",
  f7_p: "Sous-titres manuels ou auto-générés en SRT, VTT ou ASS — à côté de la vidéo, intégrés dans un .mkv portable, ou rangés dans un dossier Subtitles/.",
  f8_h: "SponsorBlock intégré",
  f8_p: "Passe ou marque les segments sponsors, intros, outros, autopromos et plus — coupe-les avec FFmpeg ou ajoute simplement des chapitres. Ton choix, par catégorie.",

  shots_eyebrow: "Voyez-le en action",
  shots_h2: "Conçu pour la clarté, pas l'encombrement.",
  shot1_alt: "Coller une URL",
  shot2_alt: "Choisir la qualité",
  shot3_alt: "Choisir où enregistrer",
  shot4_alt: "Téléchargements parallèles",
  shot5_alt: "Étape sous-titres — choisir langues, format et mode d'enregistrement",
  og_image_alt: "Icône de l'app Arroxy — application bureau pour télécharger des vidéos YouTube en 4K.",

  privacy_eyebrow: "Confidentialité",
  privacy_h2_html: "Ce qu'Arroxy <em>ne fait pas</em>.",
  privacy_sub:
    "La plupart des téléchargeurs YouTube finissent par demander vos cookies. Arroxy ne le fera jamais.",
  p1_h: "Sans connexion",
  p1_p: "Aucun compte Google. Aucune session à expirer. Zéro risque que votre compte soit signalé.",
  p2_h: "Sans cookies",
  p2_p: "Arroxy demande les mêmes tokens que n'importe quel navigateur. Rien n'est exporté, rien n'est stocké.",
  p3_h: "Sans télémétrie",
  p3_p: "Zéro analytique. Vos téléchargements, historique et fichiers restent sur votre appareil — point final.",
  p4_h: "Sans serveurs tiers",
  p4_p: "Tout le pipeline tourne en local via yt-dlp + ffmpeg. Les fichiers ne touchent jamais un serveur distant.",

  install_eyebrow: "Installer",
  install_h2: "Choisissez votre canal.",
  install_sub:
    "Téléchargement direct ou tout gestionnaire de paquets majeur — tous mis à jour automatiquement à chaque release.",
  badge_windows: "Windows",
  badge_macos: "macOS",
  badge_all: "Tous",
  winget_desc: "Recommandé pour Windows 10/11. Se met à jour avec le système.",
  scoop_desc: "Installation portable via le bucket Scoop. Aucun droit admin requis.",
  brew_desc: "Tap le cask, installation en une commande. Binaire universel (Intel + Apple Silicon).",
  direct_h: "Téléchargement direct",
  direct_desc: "Installeur NSIS, .exe portable, .dmg ou .AppImage — directement depuis GitHub Releases.",
  direct_btn: "Ouvrir les Releases →",
  copy_label: "Copier",
  copied_label: "Copié !",

  footer_made_by: "Licence MIT · Fait avec soin par",
  footer_github: "GitHub",
  footer_issues: "Issues",
  footer_releases: "Releases",
  footer_languages_label: "Langue :",
};

export const ja = {
  title: "Arroxy — 無料・オープンソースの YouTube ダウンローダー",
  description:
    "YouTube 動画を 4K、1080p60、HDR でダウンロード。無料、広告なし、ログイン不要、Cookie 不要、100% プライベート。Windows、macOS、Linux 対応。",
  og_title: "Arroxy — 無料・オープンソースの YouTube ダウンローダー",
  og_description:
    "4K · 1080p60 · HDR · Shorts。広告なし。トラッキングなし。Cookie なし。ログイン不要。",

  nav_features: "機能",
  nav_screenshots: "スクリーンショット",
  nav_install: "インストール",
  nav_download: "ダウンロード",

  hero_eyebrow: "モダン · 無料 · オープンソース",
  hero_h1_a: "YouTube 動画を",
  hero_h1_b: "フル画質でダウンロード。",
  hero_tagline:
    "YouTube が配信するすべて — 4K、1080p60、HDR、Shorts — そのままディスクへ。",
  pill_no_ads: "広告なし",
  pill_no_tracking: "トラッキングなし",
  pill_no_login: "ログイン不要",
  pill_no_cookies: "Cookie 不要",
  pill_mit: "MIT ライセンス",
  cta_download_os: "あなたの OS 向けにダウンロード",
  cta_view_github: "GitHub で見る",
  release_label: "最新リリース:",
  release_loading: "読み込み中…",

  features_eyebrow: "できること",
  features_h2: "期待されることはすべて、面倒は一切なく。",
  features_sub: "URL を貼り付けて、画質を選んで、ダウンロードをクリック。それだけ。",
  f1_h: "最大 4K UHD",
  f1_p: "2160p、1440p、1080p、720p — YouTube が提供するあらゆる解像度に加え、MP3、AAC、Opus の音声のみも対応。",
  f2_h: "60 fps と HDR を維持",
  f2_p: "高フレームレートと HDR ストリームは YouTube がエンコードしたまま — 画質劣化なし。",
  f3_h: "複数同時に",
  f3_p: "好きなだけ動画をキューに追加できます。ダウンロードパネルが各進捗を並行して表示。",
  f4_h: "自動アップデート",
  f4_p: "Arroxy は yt-dlp と ffmpeg を裏で常に最新に保ちます — YouTube の変更にも対応。",
  f5_h: "9 言語対応",
  f5_p: "English, Español, Deutsch, Français, 日本語, 中文, Русский, Українська, हिन्दी — あなたの言語を自動検出。",
  f6_h: "マルチプラットフォーム",
  f6_p: "Windows、macOS、Linux のネイティブビルド — インストーラー、ポータブル、DMG、AppImage。",
  f7_h: "字幕は思いのままに",
  f7_p: "手動または自動生成の字幕を SRT、VTT、ASS で取得 — 動画と並べて保存、ポータブルな .mkv に埋め込み、または Subtitles/ フォルダに整理。",
  f8_h: "SponsorBlock 内蔵",
  f8_p: "スポンサー、イントロ、アウトロ、自己宣伝などをスキップまたはマーク — FFmpeg でカットするか章として追加するか。カテゴリごとにあなたが決める。",

  shots_eyebrow: "実際の動作",
  shots_h2: "明快さのために設計、雑然さは排除。",
  shot1_alt: "URL を貼り付け",
  shot2_alt: "画質を選択",
  shot3_alt: "保存先を選択",
  shot4_alt: "並行ダウンロード",
  shot5_alt: "字幕ステップ — 言語・フォーマット・保存モードを選ぶ",
  og_image_alt: "Arroxy アプリアイコン — YouTube 動画を 4K でダウンロードするデスクトップアプリ。",

  privacy_eyebrow: "プライバシー",
  privacy_h2_html: "Arroxy が<em>しない</em>こと。",
  privacy_sub:
    "ほとんどの YouTube ダウンローダーは、いずれ Cookie を要求します。Arroxy は決して要求しません。",
  p1_h: "ログイン不要",
  p1_p: "Google アカウント不要。期限切れのセッションもなし。アカウントが警告される心配ゼロ。",
  p2_h: "Cookie 不要",
  p2_p: "Arroxy はブラウザと同じトークンを要求するだけ。何もエクスポートせず、何も保存しません。",
  p3_h: "テレメトリーなし",
  p3_p: "アナリティクス一切なし。ダウンロード、履歴、ファイルはすべてあなたのデバイス内に留まります。",
  p4_h: "サードパーティサーバーなし",
  p4_p: "全パイプラインが yt-dlp + ffmpeg でローカル実行。ファイルがリモートサーバーに触れることはありません。",

  install_eyebrow: "インストール",
  install_h2: "チャンネルを選んでください。",
  install_sub:
    "直接ダウンロード、または主要パッケージマネージャー経由 — すべてリリースごとに自動更新。",
  badge_windows: "Windows",
  badge_macos: "macOS",
  badge_all: "全 OS",
  winget_desc: "Windows 10/11 推奨。システムと一緒に自動更新。",
  scoop_desc: "Scoop バケット経由のポータブルインストール。管理者権限不要。",
  brew_desc: "Cask を tap してワンコマンドでインストール。ユニバーサルバイナリ (Intel + Apple Silicon)。",
  direct_h: "直接ダウンロード",
  direct_desc: "NSIS インストーラー、ポータブル .exe、.dmg、.AppImage — GitHub Releases から直接。",
  direct_btn: "Releases を開く →",
  copy_label: "コピー",
  copied_label: "コピーしました！",

  footer_made_by: "MIT ライセンス · 作者:",
  footer_github: "GitHub",
  footer_issues: "Issues",
  footer_releases: "Releases",
  footer_languages_label: "言語:",
};

export const zh = {
  title: "Arroxy — 免费开源的 YouTube 下载器",
  description:
    "以 4K、1080p60 和 HDR 下载 YouTube 视频。免费、无广告、无需登录、无需 Cookie、100% 私密。支持 Windows、macOS、Linux。",
  og_title: "Arroxy — 免费开源的 YouTube 下载器",
  og_description:
    "4K · 1080p60 · HDR · Shorts。无广告。无追踪。无 Cookie。无需登录。",

  nav_features: "功能",
  nav_screenshots: "截图",
  nav_install: "安装",
  nav_download: "下载",

  hero_eyebrow: "现代 · 免费 · 开源",
  hero_h1_a: "下载 YouTube 视频",
  hero_h1_b: "完整原画质。",
  hero_tagline:
    "YouTube 提供的一切 — 4K、1080p60、HDR、Shorts — 直接保存到你的磁盘。",
  pill_no_ads: "无广告",
  pill_no_tracking: "无追踪",
  pill_no_login: "无需登录",
  pill_no_cookies: "无 Cookie",
  pill_mit: "MIT 许可证",
  cta_download_os: "下载适合你系统的版本",
  cta_view_github: "在 GitHub 上查看",
  release_label: "最新版本:",
  release_loading: "加载中…",

  features_eyebrow: "它能做什么",
  features_h2: "一切如你所愿，毫无阻碍。",
  features_sub: "粘贴 URL，选择画质，点击下载。就这么简单。",
  f1_h: "高达 4K UHD",
  f1_p: "2160p、1440p、1080p、720p — YouTube 提供的每一种分辨率，外加 MP3、AAC、Opus 纯音频。",
  f2_h: "保留 60 fps 与 HDR",
  f2_p: "高帧率与 HDR 流原样直通，正如 YouTube 编码的那样 — 零画质损失。",
  f3_h: "多任务并行",
  f3_p: "想排多少视频就排多少。下载面板并行显示每个任务的进度。",
  f4_h: "自动更新",
  f4_p: "Arroxy 在后台保持 yt-dlp 与 ffmpeg 最新 — 应对 YouTube 的每一次变化。",
  f5_h: "9 种语言",
  f5_p: "English, Español, Deutsch, Français, 日本語, 中文, Русский, Українська, हिन्दी — 自动检测你的语言。",
  f6_h: "跨平台",
  f6_p: "Windows、macOS、Linux 原生构建 — 安装包、便携版、DMG 或 AppImage。",
  f7_h: "字幕，随你所愿",
  f7_p: "以 SRT、VTT 或 ASS 获取手动或自动生成的字幕 — 保存到视频旁边、嵌入便携的 .mkv，或整理到 Subtitles/ 子文件夹。",
  f8_h: "内置 SponsorBlock",
  f8_p: "跳过或标记赞助商、片头、片尾、自我推广等片段 — 用 FFmpeg 剪除或直接添加章节。按类别自由选择。",

  shots_eyebrow: "实际效果",
  shots_h2: "为清晰而生，拒绝杂乱。",
  shot1_alt: "粘贴 URL",
  shot2_alt: "选择画质",
  shot3_alt: "选择保存位置",
  shot4_alt: "并行下载",
  shot5_alt: "字幕步骤 — 选择语言、格式与保存方式",
  og_image_alt: "Arroxy 应用图标 — 用于以 4K 下载 YouTube 视频的桌面应用。",

  privacy_eyebrow: "隐私",
  privacy_h2_html: "Arroxy <em>不会</em>做什么。",
  privacy_sub:
    "大多数 YouTube 下载器迟早会向你索取 Cookie。Arroxy 永远不会。",
  p1_h: "无需登录",
  p1_p: "无需 Google 账号。没有会话过期问题。账号被标记的风险为零。",
  p2_h: "无 Cookie",
  p2_p: "Arroxy 请求的只是浏览器同样会请求的令牌。不导出，不保存。",
  p3_h: "无遥测",
  p3_p: "零分析。你的下载、历史和文件全部留在本地设备 — 就这样。",
  p4_h: "无第三方服务器",
  p4_p: "整个流程通过 yt-dlp + ffmpeg 在本地运行。文件永远不会经过远程服务器。",

  install_eyebrow: "安装",
  install_h2: "选择你的渠道。",
  install_sub:
    "直接下载或任意主流包管理器 — 每次发布都会自动更新。",
  badge_windows: "Windows",
  badge_macos: "macOS",
  badge_all: "全部",
  winget_desc: "推荐用于 Windows 10/11。随系统自动更新。",
  scoop_desc: "通过 Scoop bucket 便携安装。无需管理员权限。",
  brew_desc: "添加 cask，一行命令安装。通用二进制 (Intel + Apple Silicon)。",
  direct_h: "直接下载",
  direct_desc: "NSIS 安装包、便携 .exe、.dmg 或 .AppImage — 直接从 GitHub Releases 获取。",
  direct_btn: "打开 Releases →",
  copy_label: "复制",
  copied_label: "已复制！",

  footer_made_by: "MIT 许可证 · 用心制作:",
  footer_github: "GitHub",
  footer_issues: "Issues",
  footer_releases: "Releases",
  footer_languages_label: "语言:",
};

export const ru = {
  title: "Arroxy — Бесплатный загрузчик YouTube с открытым кодом",
  description:
    "Скачивайте видео с YouTube в 4K, 1080p60 и HDR. Бесплатно, без рекламы, без входа, без cookies, 100% приватно. Windows, macOS, Linux.",
  og_title: "Arroxy — Бесплатный загрузчик YouTube с открытым кодом",
  og_description:
    "4K · 1080p60 · HDR · Shorts. Без рекламы. Без слежки. Без cookies. Без входа.",

  nav_features: "Возможности",
  nav_screenshots: "Скриншоты",
  nav_install: "Установка",
  nav_download: "Скачать",

  hero_eyebrow: "Современный · Бесплатный · Open Source",
  hero_h1_a: "Скачивайте видео с YouTube",
  hero_h1_b: "в полном качестве.",
  hero_tagline:
    "Всё, что отдаёт YouTube — 4K, 1080p60, HDR, Shorts — прямо на ваш диск.",
  pill_no_ads: "Без рекламы",
  pill_no_tracking: "Без слежки",
  pill_no_login: "Без входа",
  pill_no_cookies: "Без cookies",
  pill_mit: "Лицензия MIT",
  cta_download_os: "Скачать для вашей ОС",
  cta_view_github: "Открыть на GitHub",
  release_label: "Последняя версия:",
  release_loading: "загрузка…",

  features_eyebrow: "Что он умеет",
  features_h2: "Всё, что нужно, и ничего лишнего.",
  features_sub: "Вставьте URL, выберите качество, нажмите «Скачать». Вот и всё.",
  f1_h: "До 4K UHD",
  f1_p: "2160p, 1440p, 1080p, 720p — все разрешения, которые предлагает YouTube, плюс только аудио в MP3, AAC и Opus.",
  f2_h: "60 fps и HDR без потерь",
  f2_p: "Высокая частота кадров и HDR-потоки приходят ровно так, как их кодирует YouTube — без потери качества.",
  f3_h: "Сразу несколько",
  f3_p: "Ставьте в очередь сколько угодно видео. Панель загрузок отслеживает прогресс каждого параллельно.",
  f4_h: "Автообновления",
  f4_p: "Arroxy сам поддерживает yt-dlp и ffmpeg в актуальном состоянии — работает после любых изменений YouTube.",
  f5_h: "9 языков",
  f5_p: "English, Español, Deutsch, Français, 日本語, 中文, Русский, Українська, हिन्दी — определяет ваш автоматически.",
  f6_h: "Кросс-платформенный",
  f6_p: "Нативные сборки для Windows, macOS и Linux — установщик, портативная версия, DMG или AppImage.",
  f7_h: "Субтитры — как вам удобно",
  f7_p: "Ручные или авто-сгенерированные субтитры в SRT, VTT или ASS — рядом с видео, встроенные в портативный .mkv или сложенные в подпапку Subtitles/.",
  f8_h: "SponsorBlock встроен",
  f8_p: "Пропускайте или отмечайте сегменты спонсоров, вступления, концовки, самопиар и прочее — вырезайте через FFmpeg или добавляйте главы. Ваш выбор, по каждой категории.",

  shots_eyebrow: "В деле",
  shots_h2: "Сделано для ясности, не для мусора.",
  shot1_alt: "Вставьте URL",
  shot2_alt: "Выберите качество",
  shot3_alt: "Выберите место сохранения",
  shot4_alt: "Параллельные загрузки",
  shot5_alt: "Шаг субтитров — выбор языков, формата и режима сохранения",
  og_image_alt: "Иконка приложения Arroxy — десктопное приложение для загрузки YouTube-видео в 4K.",

  privacy_eyebrow: "Приватность",
  privacy_h2_html: "Чего Arroxy <em>не делает</em>.",
  privacy_sub:
    "Большинство загрузчиков YouTube рано или поздно просят ваши cookies. Arroxy — никогда.",
  p1_h: "Без входа",
  p1_p: "Без Google-аккаунта. Без истекающих сессий. Нулевой риск, что аккаунт пометят.",
  p2_h: "Без cookies",
  p2_p: "Arroxy запрашивает те же токены, что любой браузер. Ничего не экспортируется, ничего не хранится.",
  p3_h: "Без телеметрии",
  p3_p: "Никакой аналитики. Ваши загрузки, история и файлы остаются на вашем устройстве — точка.",
  p4_h: "Без сторонних серверов",
  p4_p: "Весь конвейер работает локально через yt-dlp + ffmpeg. Файлы никогда не попадают на удалённый сервер.",

  install_eyebrow: "Установка",
  install_h2: "Выберите канал.",
  install_sub:
    "Прямая загрузка или любой популярный менеджер пакетов — все обновляются автоматически с каждым релизом.",
  badge_windows: "Windows",
  badge_macos: "macOS",
  badge_all: "Все",
  winget_desc: "Рекомендуется для Windows 10/11. Обновляется вместе с системой.",
  scoop_desc: "Портативная установка через Scoop bucket. Права администратора не нужны.",
  brew_desc: "Добавьте tap, установите одной командой. Universal Binary (Intel + Apple Silicon).",
  direct_h: "Прямая загрузка",
  direct_desc: "NSIS-установщик, портативный .exe, .dmg или .AppImage — прямо из GitHub Releases.",
  direct_btn: "Открыть Releases →",
  copy_label: "Копировать",
  copied_label: "Скопировано!",

  footer_made_by: "Лицензия MIT · Сделано с заботой:",
  footer_github: "GitHub",
  footer_issues: "Issues",
  footer_releases: "Releases",
  footer_languages_label: "Язык:",
};

export const uk = {
  title: "Arroxy — Безкоштовний завантажувач YouTube із відкритим кодом",
  description:
    "Завантажуйте відео з YouTube у 4K, 1080p60 та HDR. Безкоштовно, без реклами, без входу, без cookies, 100% приватно. Windows, macOS, Linux.",
  og_title: "Arroxy — Безкоштовний завантажувач YouTube із відкритим кодом",
  og_description:
    "4K · 1080p60 · HDR · Shorts. Без реклами. Без стеження. Без cookies. Без входу.",

  nav_features: "Можливості",
  nav_screenshots: "Скриншоти",
  nav_install: "Встановлення",
  nav_download: "Завантажити",

  hero_eyebrow: "Сучасний · Безкоштовний · Open Source",
  hero_h1_a: "Завантажуйте відео з YouTube",
  hero_h1_b: "у повній якості.",
  hero_tagline:
    "Усе, що дає YouTube — 4K, 1080p60, HDR, Shorts — прямо на ваш диск.",
  pill_no_ads: "Без реклами",
  pill_no_tracking: "Без стеження",
  pill_no_login: "Без входу",
  pill_no_cookies: "Без cookies",
  pill_mit: "Ліцензія MIT",
  cta_download_os: "Завантажити для вашої ОС",
  cta_view_github: "Дивитися на GitHub",
  release_label: "Остання версія:",
  release_loading: "завантаження…",

  features_eyebrow: "Що він робить",
  features_h2: "Усе, чого ви очікуєте, без жодного тертя.",
  features_sub: "Вставте URL, оберіть якість, натисніть «Завантажити». Та й усе.",
  f1_h: "До 4K UHD",
  f1_p: "2160p, 1440p, 1080p, 720p — усі роздільні здатності, що пропонує YouTube, плюс лише аудіо у MP3, AAC та Opus.",
  f2_h: "60 fps і HDR збережено",
  f2_p: "Високочастотні та HDR-потоки приходять саме такими, як їх кодує YouTube — без втрати якості.",
  f3_h: "Декілька одночасно",
  f3_p: "Ставте в чергу скільки завгодно відео. Панель показує прогрес кожного паралельно.",
  f4_h: "Автооновлення",
  f4_p: "Arroxy сам підтримує yt-dlp та ffmpeg актуальними — працює після будь-яких змін YouTube.",
  f5_h: "9 мов",
  f5_p: "English, Español, Deutsch, Français, 日本語, 中文, Русский, Українська, हिन्दी — визначає вашу автоматично.",
  f6_h: "Крос-платформний",
  f6_p: "Нативні збірки для Windows, macOS та Linux — інсталятор, портативна версія, DMG або AppImage.",
  f7_h: "Субтитри — як вам зручно",
  f7_p: "Ручні або авто-згенеровані субтитри у SRT, VTT чи ASS — поруч із відео, вбудовані в портативний .mkv або складені в підпапку Subtitles/.",
  f8_h: "SponsorBlock вбудовано",
  f8_p: "Пропускайте або позначайте сегменти спонсорів, вступи, кінцівки, самопіар тощо — вирізайте через FFmpeg або додавайте розділи. Ваш вибір, для кожної категорії.",

  shots_eyebrow: "У дії",
  shots_h2: "Зроблено заради ясності, а не для безладу.",
  shot1_alt: "Вставте URL",
  shot2_alt: "Оберіть якість",
  shot3_alt: "Оберіть місце збереження",
  shot4_alt: "Паралельні завантаження",
  shot5_alt: "Крок субтитрів — вибір мов, формату та режиму збереження",
  og_image_alt: "Іконка застосунку Arroxy — десктопний застосунок для завантаження YouTube-відео у 4K.",

  privacy_eyebrow: "Приватність",
  privacy_h2_html: "Що Arroxy <em>не робить</em>.",
  privacy_sub:
    "Більшість завантажувачів YouTube рано чи пізно просять ваші cookies. Arroxy — ніколи.",
  p1_h: "Без входу",
  p1_p: "Без Google-акаунта. Без сесій, що закінчуються. Нульовий ризик блокування акаунта.",
  p2_h: "Без cookies",
  p2_p: "Arroxy просить ті самі токени, що й будь-який браузер. Нічого не експортується й не зберігається.",
  p3_h: "Без телеметрії",
  p3_p: "Жодної аналітики. Ваші завантаження, історія та файли залишаються на вашому пристрої — крапка.",
  p4_h: "Без сторонніх серверів",
  p4_p: "Уся обробка йде локально через yt-dlp + ffmpeg. Файли ніколи не торкаються віддаленого сервера.",

  install_eyebrow: "Встановлення",
  install_h2: "Оберіть канал.",
  install_sub:
    "Пряме завантаження або будь-який популярний менеджер пакетів — усі оновлюються автоматично з кожним релізом.",
  badge_windows: "Windows",
  badge_macos: "macOS",
  badge_all: "Усі",
  winget_desc: "Рекомендовано для Windows 10/11. Оновлюється разом із системою.",
  scoop_desc: "Портативна установка через Scoop bucket. Прав адміністратора не потрібно.",
  brew_desc: "Додайте tap, встановіть однією командою. Universal Binary (Intel + Apple Silicon).",
  direct_h: "Пряме завантаження",
  direct_desc: "NSIS-інсталятор, портативний .exe, .dmg або .AppImage — прямо з GitHub Releases.",
  direct_btn: "Відкрити Releases →",
  copy_label: "Копіювати",
  copied_label: "Скопійовано!",

  footer_made_by: "Ліцензія MIT · Зроблено з турботою:",
  footer_github: "GitHub",
  footer_issues: "Issues",
  footer_releases: "Releases",
  footer_languages_label: "Мова:",
};

export const hi = {
  title: "Arroxy — मुफ़्त ओपन-सोर्स YouTube डाउनलोडर",
  description:
    "YouTube वीडियो को 4K, 1080p60 और HDR में डाउनलोड करें। मुफ़्त, विज्ञापन रहित, बिना लॉगिन, बिना कुकीज़, 100% निजी। Windows, macOS, Linux।",
  og_title: "Arroxy — मुफ़्त ओपन-सोर्स YouTube डाउनलोडर",
  og_description:
    "4K · 1080p60 · HDR · Shorts। कोई विज्ञापन नहीं। कोई ट्रैकिंग नहीं। कोई कुकीज़ नहीं। कोई लॉगिन नहीं।",

  nav_features: "विशेषताएँ",
  nav_screenshots: "स्क्रीनशॉट",
  nav_install: "इंस्टॉल",
  nav_download: "डाउनलोड",

  hero_eyebrow: "आधुनिक · मुफ़्त · ओपन सोर्स",
  hero_h1_a: "YouTube वीडियो डाउनलोड करें",
  hero_h1_b: "पूर्ण गुणवत्ता में।",
  hero_tagline:
    "जो भी YouTube परोसता है — 4K, 1080p60, HDR, Shorts — सीधे आपकी डिस्क पर।",
  pill_no_ads: "कोई विज्ञापन नहीं",
  pill_no_tracking: "कोई ट्रैकिंग नहीं",
  pill_no_login: "कोई लॉगिन नहीं",
  pill_no_cookies: "कोई कुकीज़ नहीं",
  pill_mit: "MIT लाइसेंस",
  cta_download_os: "अपने OS के लिए डाउनलोड करें",
  cta_view_github: "GitHub पर देखें",
  release_label: "नवीनतम रिलीज़:",
  release_loading: "लोड हो रहा है…",

  features_eyebrow: "यह क्या करता है",
  features_h2: "जो आप उम्मीद करते हैं वह सब, बिना किसी अड़चन के।",
  features_sub: "URL पेस्ट करें, गुणवत्ता चुनें, डाउनलोड पर क्लिक करें। बस इतना।",
  f1_h: "4K UHD तक",
  f1_p: "2160p, 1440p, 1080p, 720p — हर वह रिज़ॉल्यूशन जो YouTube देता है, साथ ही केवल-ऑडियो MP3, AAC और Opus।",
  f2_h: "60 fps और HDR सुरक्षित",
  f2_p: "हाई फ्रेम-रेट और HDR स्ट्रीम बिल्कुल वैसी ही आती हैं जैसी YouTube एनकोड करता है — बिना गुणवत्ता के नुकसान।",
  f3_h: "एक साथ कई",
  f3_p: "जितने चाहें उतने वीडियो कतार में लगाएँ। डाउनलोड पैनल हर एक की प्रगति समानांतर में दिखाता है।",
  f4_h: "स्वचालित अपडेट",
  f4_p: "Arroxy yt-dlp और ffmpeg को पीछे से ताज़ा रखता है — YouTube के हर बदलाव के साथ चलता है।",
  f5_h: "9 भाषाएँ",
  f5_p: "English, Español, Deutsch, Français, 日本語, 中文, Русский, Українська, हिन्दी — आपकी भाषा अपने आप पहचानता है।",
  f6_h: "क्रॉस-प्लेटफ़ॉर्म",
  f6_p: "Windows, macOS और Linux के लिए नेटिव बिल्ड — इंस्टॉलर, पोर्टेबल, DMG या AppImage।",
  f7_h: "सबटाइटल, आपके अंदाज़ में",
  f7_p: "SRT, VTT या ASS में मैनुअल या ऑटो-जेनरेटेड सबटाइटल — वीडियो के बग़ल में सेव करें, पोर्टेबल .mkv में एम्बेड करें, या Subtitles/ फ़ोल्डर में रखें।",
  f8_h: "SponsorBlock बिल्ट-इन",
  f8_p: "स्पॉन्सर सेगमेंट, इंट्रो, आउट्रो, सेल्फ-प्रोमो और अन्य को स्किप या मार्क करें — FFmpeg से काटें या बस चैप्टर जोड़ें। हर कैटेगरी के लिए आपकी पसंद।",

  shots_eyebrow: "क्रिया में देखें",
  shots_h2: "स्पष्टता के लिए बना है, अव्यवस्था के लिए नहीं।",
  shot1_alt: "URL पेस्ट करें",
  shot2_alt: "अपनी गुणवत्ता चुनें",
  shot3_alt: "सहेजने का स्थान चुनें",
  shot4_alt: "समानांतर डाउनलोड",
  shot5_alt: "सबटाइटल स्टेप — भाषाएँ, फ़ॉर्मैट और सेव मोड चुनें",
  og_image_alt: "Arroxy ऐप आइकन — YouTube वीडियो को 4K में डाउनलोड करने के लिए डेस्कटॉप ऐप।",

  privacy_eyebrow: "गोपनीयता",
  privacy_h2_html: "Arroxy जो <em>नहीं</em> करता है।",
  privacy_sub:
    "अधिकांश YouTube डाउनलोडर अंततः आपकी कुकीज़ माँगते हैं। Arroxy कभी नहीं माँगेगा।",
  p1_h: "कोई लॉगिन नहीं",
  p1_p: "कोई Google खाता नहीं। कोई समाप्त होने वाली सत्र नहीं। आपके खाते पर ध्वजांकित होने का शून्य जोखिम।",
  p2_h: "कोई कुकीज़ नहीं",
  p2_p: "Arroxy वही टोकन माँगता है जो कोई भी ब्राउज़र। कुछ निर्यात नहीं, कुछ संग्रहीत नहीं।",
  p3_h: "कोई टेलीमेट्री नहीं",
  p3_p: "शून्य एनालिटिक्स। आपके डाउनलोड, इतिहास और फ़ाइलें आपके डिवाइस पर ही रहती हैं — पूरी बात।",
  p4_h: "कोई तृतीय-पक्ष सर्वर नहीं",
  p4_p: "पूरी पाइपलाइन yt-dlp + ffmpeg के माध्यम से स्थानीय रूप से चलती है। फ़ाइलें कभी रिमोट सर्वर को नहीं छूतीं।",

  install_eyebrow: "इंस्टॉल",
  install_h2: "अपना चैनल चुनें।",
  install_sub:
    "सीधा डाउनलोड या कोई भी प्रमुख पैकेज मैनेजर — हर रिलीज़ के साथ स्वचालित रूप से अपडेट।",
  badge_windows: "Windows",
  badge_macos: "macOS",
  badge_all: "सभी",
  winget_desc: "Windows 10/11 के लिए अनुशंसित। सिस्टम के साथ ऑटो-अपडेट।",
  scoop_desc: "Scoop bucket के माध्यम से पोर्टेबल इंस्टॉल। एडमिन अधिकार आवश्यक नहीं।",
  brew_desc: "Cask टैप करें, एक कमांड से इंस्टॉल करें। यूनिवर्सल बाइनरी (Intel + Apple Silicon)।",
  direct_h: "सीधा डाउनलोड",
  direct_desc: "NSIS इंस्टॉलर, पोर्टेबल .exe, .dmg, या .AppImage — सीधे GitHub Releases से।",
  direct_btn: "Releases खोलें →",
  copy_label: "कॉपी करें",
  copied_label: "कॉपी हो गया!",

  footer_made_by: "MIT लाइसेंस · सावधानी से बनाया गया:",
  footer_github: "GitHub",
  footer_issues: "Issues",
  footer_releases: "Releases",
  footer_languages_label: "भाषा:",
};

// Locale registry. Order = display order in the language picker.
// `dir` is the path under docs/ ("" = root for English).
// `ogLocale` is the canonical Open Graph locale tag (BCP 47 with underscore).
export const LOCALES = [
  { code: "en", name: "English",   dir: "",   ogLocale: "en_US", strings: en },
  { code: "es", name: "Español",   dir: "es", ogLocale: "es_ES", strings: es },
  { code: "de", name: "Deutsch",   dir: "de", ogLocale: "de_DE", strings: de },
  { code: "fr", name: "Français",  dir: "fr", ogLocale: "fr_FR", strings: fr },
  { code: "ja", name: "日本語",     dir: "ja", ogLocale: "ja_JP", strings: ja },
  { code: "zh", name: "中文",       dir: "zh", ogLocale: "zh_CN", strings: zh },
  { code: "ru", name: "Русский",   dir: "ru", ogLocale: "ru_RU", strings: ru },
  { code: "uk", name: "Українська", dir: "uk", ogLocale: "uk_UA", strings: uk },
  { code: "hi", name: "हिन्दी",      dir: "hi", ogLocale: "hi_IN", strings: hi },
];
